# Generated by Django 5.2.14 on 2026-06-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_include_meeting_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_error',
            field=models.TextField(blank=True, verbose_name='erreur email'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email envoye le'),
        ),
        migrations.AddField(
            model_name='reminderpreference',
            name='email_enabled',
            field=models.BooleanField(default=True, verbose_name='recevoir les rappels par email'),
        ),
    ]
